version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    # env_file:
    #   - .env
    environment: 
        - TG_TOKEN_KEY=${TG_TOKEN_KEY}
        - TG_CHAT_ID=${TG_CHAT_ID}
        - PORT=${PORT}
        - AUTH_USERNAME=${AUTH_USERNAME}
        - AUTH_PASSWORD=${AUTH_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_HOST=${DB_HOST}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - DB_TYPE=${DB_TYPE}
